version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    networks:
      reverse-proxy:
        aliases:
          - proxy.local
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      
  api:
    build: .
    container_name: api
    ports:
      - "9000:9000"
    volumes:
      - ./server:/app/server
    command: bash -c "cd server && node api/app.js"
    environment:
      - VIRTUAL_HOST=api.local

  data:
    build: .
    container_name: data
    ports:
     - "8080:8080"
    volumes:
      - ./server:/app/server
    command: bash -c "cd server && node data/app.js"
    environment:
      - VIRTUAL_HOST=data.local

volumes:
  server:

networks:
  reverse-proxy: